build-job:
  stage: build
  script:
    - echo "Starting build on runner $CI_RUNNER_ID for commit $CI_COMMIT_SHORT_SHA"
    - ls -la
    - cmake --version
    - g++ --version
    - date
    - mkdir build
    - cd build
    - cmake ..
    - make -j 4
    - make -j 4 unit_tests
  tags:
    - build
  artifacts:
    paths:
      - "build/"
    expire_in: 2 day

test-job:
  stage: test
  script:
    - echo "Starting unit_tests on runner $CI_RUNNER_ID for commit $CI_COMMIT_SHORT_SHA"
    - ls -la 
    - cmake --version
    - g++ --version
    - date
    - cd build
    - ./unit_tests
  dependencies:
    - build-job
  tags:
    - build
 
functional-test-job:
  stage: test
  script:
    - cd functional_test
    - pip install --user -r requirements.txt
    - chmod u+x functional_test.py
    - ./functional_test.py
  dependencies:
    - build-job
  tags:
    - simulation
  artifacts:
    name: "$CI_COMMIT_REF_NAME-sim_log.txt"
    paths:
      - functional_test/simulation_logs.txt
    expire_in: 2 weeks
