stages:
  - build_deps
  - build
  - test
  - calibration
  - simulation
  - analysis
  - publish

variables:
  CALIBRATION_CONFIG_PATH: "./exp_configurations"
  CALIBRATION_CONFIGURATION_BASE: "$CALIBRATION_CONFIG_PATH/theta_config.yml"
  CALIBRATION_DATASET_PATH: "./exp_datasets"
  CALIBRATION_DATASET: "theta2022_week38"
  CALIBRATION_DATASET_EXT: ".yaml"
  CALIBRATION_BUILD_PATH: "../build"
  CALIBRATION_RUNS: 10

build_simgrid_v3.34:
  stage: build_deps
  parallel: 3
  script: 
    - git config --global --add safe.directory /builds/deps/simgrid
    - cd /builds/deps/simgrid
    - git checkout v3.34
    - sudo cmake -DCMAKE_INSTALL_PREFIX=/opt/simgrid .
    - sudo make -j 4
    - sudo make install
  tags:
    - fives
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[sg3.34\]$/
    - if: $CI_COMMIT_MESSAGE =~ /\[stable\]$/

build_wrench_master:
  stage: build_deps
  parallel: 3
  script:
    - git config --global --add safe.directory /builds/deps/wrench
    - cd /builds/deps/wrench/build
    - git checkout master
    - sudo SimGrid_PATH=/opt/simgrid cmake ..
    - sudo make -j 4
    - sudo make install
  tags:
    - fives
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[wrenchmaster\]$/
    - if: $CI_COMMIT_MESSAGE =~ /\[stable\]$/

build_simgrid_master:
  stage: build_deps
  parallel: 3
  script: 
    - git config --global --add safe.directory /builds/deps/simgrid
    - cd /builds/deps/simgrid
    - git checkout master
    - git pull origin master
    - sudo cmake -DCMAKE_INSTALL_PREFIX=/opt/simgrid .
    - sudo make -j 4
    - sudo make install
  tags:
    - fives
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[sg_master\]$/
    - if: $CI_COMMIT_MESSAGE =~ /\[exp\]$/

build_wrench_simgrid_master:
  stage: build_deps
  parallel: 3
  script:
    - git config --global --add safe.directory /builds/deps/wrench
    - cd /builds/deps/wrench/
    - git checkout simgrid_master
    - cd build/
    - sudo SimGrid_PATH=/opt/simgrid cmake ..
    - sudo make -j 4
    - sudo make install
  tags:
    - fives
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[wrench_sgmaster\]$/
    - if: $CI_COMMIT_MESSAGE =~ /\[exp\]$/

build-job:
  stage: build
  script:
    - echo "Starting build on runner $CI_RUNNER_ID for commit $CI_COMMIT_SHORT_SHA"
    - ls -la
    - cmake --version
    - g++ --version
    - date
    - mkdir build
    - cd build
    - cmake ..
    - make -j 4
    - make -j 4 unit_tests
  tags:
    - build
  artifacts:
    paths:
      - "build/fives_wrench"
      - "build/unit_tests"  
    expire_in: 2 days

test-job:
  stage: test
  script:
    - echo "Starting unit_tests on runner $CI_RUNNER_ID for commit $CI_COMMIT_SHORT_SHA"
    - date
    - cd build
    - ./unit_tests
  dependencies:
    - build-job
  tags:
    - build
  allow_failure: true
 
functional-test-job:
  stage: test
  script:
    - cd functional_test
    - pip install --user --upgrade pip
    - pip install --user -r requirements.txt
    - chmod u+x functional_test.py
    - ./functional_test.py
  dependencies:
    - build-job
  tags:
    - simulation
  artifacts:
    name: "$CI_COMMIT_REF_NAME-CI_COMMIT_SHORT_SHA-sim_log"
    paths:
      - functional_test/simulation_logs.txt
    expire_in: 2 weeks
  allow_failure: true

calibration-job:
  stage: calibration
  script:
    - cd results
    - mkdir exp_results
    - pip install --user --upgrade pip
    - pip install --user -r requirements.txt
    - chmod u+x run_calibration_parallel.py
    - ./run_calibration_parallel.py
  tags:
    - simulation
  dependencies:
    - build-job
  artifacts:
    name: "$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA-calibrated_config"
    paths:
      - results/$CALIBRATION_CONFIG_PATH/calibrated_config.yaml
      - results/$CALIBRATION_CONFIG_PATH/exp_config_*
    expire_in: 26 weeks
  allow_failure: false

calibrated-simulation-job:
  stage: simulation
  script:
    - cd build
    - echo "../results/$CALIBRATION_CONFIG_PATH/calibrated_config.yaml"
    - cat ../results/$CALIBRATION_CONFIG_PATH/calibrated_config.yaml
    - echo "../results/$CALIBRATION_DATASET_PATH/$CALIBRATION_DATASET$CALIBRATION_DATASET_EXT"
    - cat ../results/$CALIBRATION_DATASET_PATH/$CALIBRATION_DATASET$CALIBRATION_DATASET_EXT
    - pwd
    - ls -lah .
    - ./fives_wrench ../results/$CALIBRATION_CONFIG_PATH/calibrated_config.yaml ../results/$CALIBRATION_DATASET_PATH/$CALIBRATION_DATASET$CALIBRATION_DATASET_EXT calibration
    - mv ./simulatedJobs_* ./calibrated_simulatedJobs_$CALIBRATION_DATASET$CALIBRATION_DATASET_EXT
  tags:
    - simulation
  dependencies:
    - calibration-job
    - build-job
  artifacts:
    name: "$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA-calibrated_trace"
    paths:
      - build/calibrated_simulatedJobs_$CALIBRATION_DATASET$CALIBRATION_DATASET_EXT
    expire_in: 26 weeks
  allow_failure: false

analysis-job:
  stage: analysis
  script:
    - cd results
    - pip install --user --upgrade pip
    - pip install --user -r requirements.txt
    - chmod u+x run_analysis.py
    - ./run_analysis.py ../build/calibrated_simulatedJobs_$CALIBRATION_DATASET$CALIBRATION_DATASET_EXT
  tags:
    - simulation
  dependencies:
    - build-job
    - calibrated-simulation-job
  artifacts:
    name: "${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}-calibration_analysis"
    paths:
      - results/${CI_PIPELINE_ID}_metrics.yaml
      - results/${CI_PIPELINE_ID}_runtime.pdf
      - results/${CI_PIPELINE_ID}_runtime.png
      - results/${CI_PIPELINE_ID}_iotime.pdf
      - results/${CI_PIPELINE_ID}_iotime.png
      - results/${CI_PIPELINE_ID}_iovolume.pdf
      - results/${CI_PIPELINE_ID}_iovolume.png
      - results/${CI_PIPELINE_ID}_schedule.pdf
      - results/${CI_PIPELINE_ID}_schedule.png
    expire_in: 26 weeks
  allow_failure: false

pages:
  stage: publish
  variables:
    MAX_PIPELINES: 7
  script:
    - cd results
    - tree .
    - mkdir -p public/static
    - mv ${CALIBRATION_CONFIG_PATH}/calibrated_config.yaml ./${CI_PIPELINE_ID}_calibrated_config.yaml
    - mv ./${CI_PIPELINE_ID}_runtime.png public/static/${CI_PIPELINE_ID}_runtime.png
    - mv ./${CI_PIPELINE_ID}_iotime.png public/static/${CI_PIPELINE_ID}_iotime.png
    - mv ./${CI_PIPELINE_ID}_iovolume.png public/static/${CI_PIPELINE_ID}_iovolume.png
    - mv ./${CI_PIPELINE_ID}_schedule.png public/static/${CI_PIPELINE_ID}_schedule.png
    - tree . 
    - chmod u+x build_pages.py
    - ./build_pages.py ${PAGES_TOKEN}
    - tree ./public
    - mv public ..
  dependencies:
    - analysis-job
    - calibrated-simulation-job
    - calibration-job
  artifacts:
    paths:
      - public
  tags:
    - simulation
