stages:
  - build_deps
  - build
  - test
  - calibration

variables:
  CALIBRATION_CONFIG_PATH: "./exp_configurations"
  CALIBRATION_CONFIGURATION_BASE: "$CALIBRATION_CONFIG_PATH/theta_config.yml"
  CALIBRATION_DATASET_PATH: "./exp_datasets"
  CALIBRATION_DATASET: "theta2022_week4_tiny"
  CALIBRATION_DATASET_EXT: ".yaml"
  CALIBRATION_BUILD_PATH: "../build"

build_simgrid_v3.34:
  stage: build_deps
  parallel: 3
  script: 
    - git config --global --add safe.directory /builds/deps/simgrid
    - cd /builds/deps/simgrid
    - git checkout v3.34
    - sudo cmake -DCMAKE_INSTALL_PREFIX=/opt/simgrid .
    - sudo make -j 4
    - sudo make install
  tags:
    - storalloc
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[sg3.34\]$/
    - if: $CI_COMMIT_MESSAGE =~ /\[stable\]$/

build_wrench_master:
  stage: build_deps
  parallel: 3
  script:
    - git config --global --add safe.directory /builds/deps/wrench
    - cd /builds/deps/wrench/build
    - sudo SimGrid_PATH=/opt/simgrid cmake ..
    - sudo make -j 4
    - sudo make install
  tags:
    - storalloc
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[wrenchmaster\]$/
    - if: $CI_COMMIT_MESSAGE =~ /\[stable\]$/

build_simgrid_master:
  stage: build_deps
  parallel: 3
  script: 
    - git config --global --add safe.directory /builds/deps/simgrid
    - cd /builds/deps/simgrid
    - git checkout master
    - git pull origin master
    - sudo cmake -DCMAKE_INSTALL_PREFIX=/opt/simgrid .
    - sudo make -j 4
    - sudo make install
  tags:
    - storalloc
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[sg_master\]$/
    - if: $CI_COMMIT_MESSAGE =~ /\[exp\]$/

build_wrench_simgrid_master:
  stage: build_deps
  parallel: 3
  script:
    - git config --global --add safe.directory /builds/deps/wrench
    - cd /builds/deps/wrench/
    - git checkout simgrid_master
    - cd build/
    - sudo SimGrid_PATH=/opt/simgrid cmake ..
    - sudo make -j 4
    - sudo make install
  tags:
    - storalloc
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[wrench_sgmaster\]$/
    - if: $CI_COMMIT_MESSAGE =~ /\[exp\]$/

build-job:
  stage: build
  script:
    - echo "Starting build on runner $CI_RUNNER_ID for commit $CI_COMMIT_SHORT_SHA"
    - ls -la
    - cmake --version
    - g++ --version
    - date
    - mkdir build
    - cd build
    - cmake ..
    - make -j 4
    - make -j 4 unit_tests
  tags:
    - build
  artifacts:
    paths:
      - "build/"
    expire_in: 2 days

test-job:
  stage: test
  script:
    - echo "Starting unit_tests on runner $CI_RUNNER_ID for commit $CI_COMMIT_SHORT_SHA"
    - ls -la 
    - cmake --version
    - g++ --version
    - date
    - cd build
    - ./unit_tests
  dependencies:
    - build-job
  tags:
    - build
 
functional-test-job:
  stage: test
  script:
    - cd functional_test
    - pip install --user --upgrade pip
    - pip install --user -r requirements.txt
    - chmod u+x functional_test.py
    - ./functional_test.py
  dependencies:
    - build-job
  tags:
    - simulation
  artifacts:
    name: "$CI_COMMIT_REF_NAME-CI_COMMIT_SHORT_SHA-sim_log"
    paths:
      - functional_test/simulation_logs.txt
    expire_in: 2 weeks

calibration-job:
  stage: calibration
  variables:
    CALIBRATION_RUNS: 25
  script:
    - cd results
    - mkdir exp_results
    - pip install --user --upgrade pip
    - pip install --user -r requirements.txt
    - chmod u+x run_calibration.py
    - ./run_calibration.py
  tags:
    - simulation
  dependencies:
    - build-job
    - functional-test-job
  artifacts:
    name: "$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA-calibrated_config"
    paths:
      - results/$CALIBRATION_CONFIG_PATH/calibration_config.yaml
    expire_in: 4 weeks
  allow_failure: false

calibrated-simulation-job:
  stage: calibration
  script:
    - cd build
    - cat ../results/$CALIBRATION_CONFIG_PATH/calibration_config.yaml
    - cat ../results/$CALIBRATION_DATASET_PATH/$CALIBRATION_DATASET$CALIBRATION_DATASET_EXT
    - ./storalloc-wrench ../results/$CALIBRATION_CONFIG_PATH/calibration_config.yaml ../results/$CALIBRATION_DATASET_PATH/$CALIBRATION_DATASET$CALIBRATION_DATASET_EXT calibration
    - ls -lah build
    - mv build/simulatedJobs_* ./calibrated_simulatedJobs_$CALIBRATION_DATASET$CALIBRATION_DATASET_EXT
  tags:
    - simulation
  dependencies:
    - calibration-job
    - build-job
  artifacts:
    name: "$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA-calibrated_trace"
    paths:
      - ./calibrated_simulatedJobs_$CALIBRATION_DATASET$CALIBRATION_DATASET_EXT
    expire_in: 4 weeks
  allow_failure: false

analysis-job:
  stage: calibration
  script:
    - cd results
    - pip install --user --upgrade pip
    - pip install --user -r requirements.txt
    - chmod u+x run_analysis.py
    - ./run_analysis.py ./calibrated_simulatedJobs_$CALIBRATION_DATASET$CALIBRATION_DATASET_EXT > analysis.txt
  tags:
    - simulation
  dependencies:
    - calibrated-simulation-job
  artifacts:
    name: "$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA-calibration_analysis"
    paths:
      - results/analysis.txt
    expire_in: 4 weeks
  allow_failure: false