---

general:
  bandwidth: 1 # GBps
  config_version: 0.0.1
  config_name: StorAlloc_Test
storage:
  disk_templates:
    - &hdd_capa
      id: hdd_capa
      capacity: 4000  # GB
      read_bw: 100    # MBps
      write_bw: 50    # MBps
      mount_prefix: /dev/hdd
    - &ssd_perf
      id: ssd_perf
      capacity: 960   # GB
      read_bw: 1000   # MBps
      write_bw: 500   # MBps
      mount_prefix: /dev/ssd
  node_templates:
    - &node_capa
      id: capacity
      disks:
        - quantity: 16
          template: *hdd_capa
        - quantity: 4
          template: *ssd_perf
  nodes:
    - quantity: 40
      template: *node_capa
dragonfly:
  groups: 12       # Entire Dragonfly zone
  group_links: 2
  chassis: 6       # per group
  chassis_links: 2
  routers: 16      # per chassis
  router_links: 2
  nodes: 4         # per router
  node_local_storage:
    enabled: no       # Not implemented yet anyway
    nb_disks: 1
    capacity: 128# GB
    read_bw: 1000 # MBps
    write_bw: 500 # MBps

...
