allocator: lustre
general:
  config_name: Storalloc_ParaCalib2024-4-10-1300__40
  config_version: 0.0.1
  max_stripe_size: 100048576
  preload_percent: 0.0
  walltime_extension: 1.0
lustre:
  lq_prio_free: 232
  lq_threshold_rr: 43
  max_chunks_per_ost: 66
  max_nb_ost: 2000
  stripe_count: 1
  stripe_count_high_read_add: 1
  stripe_count_high_thresh_read: 48612003
  stripe_count_high_thresh_write: 134574976
  stripe_count_high_write_add: 3
  stripe_size: 268435456
network:
  bandwidth_backbone: 9TBps
  bandwidth_backbone_ctrl: 12.5GBps
  bandwidth_backbone_perm_storage: 80GBps
  bandwidth_backbone_storage: 310GBps
  link_latency: 24us
outputs:
  io_actions_prefix: io_actions_ts_
  job_filename_prefix: simulatedJobs_
  storage_svc_prefix: storage_services_operations_
permanent_storage:
  capacity: 3050TB
  disk_id: perm_disk0
  io_buffer_size: 536870912B
  mount_prefix: /dev/disk0
  read_bw: 20GBps
  read_path: read/
  write_bw: 10GBps
  write_path: write/
storage:
  cleanup_threshold: 0.75
  io_buffer_size: 536870912B
  nb_files_per_read: 21
  nb_files_per_write: 14
  nodes:
  - quantity: 360
    template:
      disks:
      - quantity: 4
        template:
          capacity: 16000
          id: raid_OSS
          mount_prefix: /dev/hdd
          read_bw: 4440
          write_bw: 4120
      id: lustre_OSS
  non_linear_coef_read: 15.5
  non_linear_coef_write: 51.8
  read_bytes_preload_thres: 1000000000
  read_node_thres: 117243113
  read_variability: 1.0
  static_read_overhead_seconds: 3
  static_write_overhead_seconds: 3
  write_bytes_copy_thres: 2000000000
  write_node_thres: 143657786
  write_variability: 1.0
torus:
  core_count: 64
  flops: 300Gf
  max_compute_nodes: 13432
  ram: 32
