---

# Test config for a tiny Lustre filesystem
# - 1 node with 3 OST
# - 1 node with 5 OST
# - Small compute system on the side

general:
  bandwidth: 25000MBps    # 200Gbps backbone...
  config_version: 0.0.1
  config_name: StorAlloc_Lustre_TEST
  max_stripe_size: 640000000    # Max size for allocation stripes (in bytes) (when striping is done at CSS level)
storage:
  disk_templates:
    - &raid_OSS
      id: raid_OSS
      capacity: 20000    # GB
      read_bw: 1000    # MBps
      write_bw: 500    # MBps
      mount_prefix: /dev/hdd
  node_templates:
    - &node_capa_A
      id: lustre_OSS_A
      disks:
        - quantity: 3
          template: *raid_OSS
    - &node_capa_B
      id: lustre_OSS_B
      disks:
        - quantity: 5
          template: *raid_OSS
  nodes:
    - quantity: 1
      template: *node_capa_A
    - quantity: 1
      template: *node_capa_B
dragonfly:
  groups: 2         # Entire Dragonfly zone
  group_links: 2
  chassis: 2        # per group
  chassis_links: 2
  routers: 2        # per chassis
  router_links: 2
  nodes: 2          # per router
  node_local_storage:
    enabled: no     # Not implemented yet anyway
    nb_disks: 1
    capacity: 8 # GB
    read_bw: 1000 # MBps
    write_bw: 500 # MBps
allocator: lustre
lustre:
  lq_threshold_rr: 43
  lq_prio_free: 232
  max_nb_ost: 2000
  stripe_size: 40000000
...
