---

general:
  bandwidth: 25000MBps    # 200Gbps backbone...
  config_version: 0.0.1
  config_name: StorAlloc_Test
  max_stripe_size: 960000000    # Max size for allocation stripes (in bytes)
storage:
  disk_templates:
    - &hdd_capa
      id: hdd_capa
      capacity: 200   # GB
      read_bw: 100    # MBps
      write_bw: 50    # MBps
      mount_prefix: /dev/hdd
    - &ssd_perf
      id: ssd_perf
      capacity: 96    # GB
      read_bw: 1000   # MBps
      write_bw: 500   # MBps
      mount_prefix: /dev/ssd
  node_templates:
    - &node_capa
      id: capacity
      disks:
        - quantity: 1
          template: *ssd_perf
        - quantity: 2
          template: *hdd_capa
  nodes:
    - quantity: 4
      template: *node_capa
dragonfly:
  groups: 2         # Entire Dragonfly zone
  group_links: 3
  chassis: 4        # per group
  chassis_links: 5
  routers: 6        # per chassis
  router_links: 7
  nodes: 8          # per router
  node_local_storage:
    enabled: no     # Not implemented yet anyway
    nb_disks: 1
    capacity: 128 # GB
    read_bw: 1000 # MBps
    write_bw: 500 # MBps
allocator: rr
...
