---

# Test config for a tiny Lustre filesystem
# - 2 HDD per node (200GB each)
# - 8 nodes
# - Small compute system on the side

general:
  config_name: StorAlloc_Test_Lustre_base
  config_version: 0.0.1
  max_stripe_size: 100048576          # Max size for allocation stripes (in bytes) (when striping is done at CSS level, so not used here)
  preload_percent: 0.0
  amdahl: 0.5                         # From 0 to 1, degree of // in compute tasks
  walltime_extension: 1.2             # The final walltime passed to the batch sched will be walltime * walltime_extension
network:
  bandwidth_backbone: 9TBps
  bandwidth_backbone_storage: 25000MBps
  bandwidth_backbone_perm_storage: 90GBps
  bandwidth_backbone_ctrl: 12.5GBps
  link_latency: 24us
storage:
  read_variability: 1.0             # read AND write set to 1.0 to deactivate
  write_variability: 1.0
  non_linear_coef_read: 0.9         # read AND write set to 1.0 to deactivate
  non_linear_coef_write: 0.6
  nb_files_per_read: 2
  nb_files_per_write: 2
  read_node_thres: 50000000
  write_node_thres: 40000000
  io_buffer_size: 1GB
  read_bytes_preload_thres: 100000000
  write_bytes_copy_thres:  2000000000
  static_read_overhead_seconds: 0
  static_write_overhead_seconds: 0
  cleanup_threshold: 0.0
  disk_templates:
    - &raid_OSS
      id: raid_OSS
      capacity: 200    # GB
      read_bw: 1000    # MBps
      write_bw: 500    # MBps
      mount_prefix: /dev/hdd
  node_templates:
    - &node_capa
      id: lustre_OSS
      disks:
        - quantity: 2
          template: *raid_OSS
  nodes:
    - quantity: 8
      template: *node_capa
permanent_storage:
  read_bw: 10000MBps   # ALCF Tape archive cache speed is 90Gbps / and also the link between HDR and FDR is 100GBps. Here we reduce the link speed
  write_bw: 10000MBps  # Same
  capacity: 10000TB  # Tape capacity is 305 PB
  mount_prefix: /dev/disk0
  read_path: read/
  write_path: write/
  disk_id: perm_disk0
  io_buffer_size: 1GB
dragonfly:          # See https://simgrid.org/doc/latest/Platform_examples.html - Dragonfly
  groups: 2        # Entire Dragonfly zone (should be 4392 nodes in total, we use slightly more)
  group_links: 2
  chassis: 2        # Per group
  chassis_links: 2
  routers: 2       # Per chassis
  router_links: 2
  nodes: 2          # Per router
  core_count: 64    # Compute node core count - unused
  ram: 192          # GB Compute node ram
  flops: 2.2Tf      # Flops for each compute node
  max_compute_nodes: 4392
  node_local_storage:
    enabled: no     # Not implemented yet anyway
    nb_disks: 1
    capacity: 128 # GB
    read_bw: 1000 # MBps      # https://docs.alcf.anl.gov/data-management/filesystem-and-storage/file-systems/
    write_bw: 500 # MBps      # https://www.alcf.anl.gov/sites/default/files/2022-08/CompPerfWorkshop_May2022_IOopt_mcpheeters.pdf
allocator: lustre
lustre:
  lq_threshold_rr: 43     # lustre default
  lq_prio_free: 232       # lustre default
  stripe_size: 40000000    # Default size of each read / write before switching to another stripe on a different OST (from https://www.alcf.anl.gov/sites/default/files/2022-08/CompPerfWorkshopq_May2022_IOopt_mcpheeters.pdf)
  stripe_count: 1         # Default number of OSTs used for each IO operation
  max_chunks_per_ost: 80   # Maximum number of file parts / allocation chunks on each OSTs (not a Lustre parameter, but used to speed up simulation at the cost of precision)
outputs:
  job_filename_prefix: simulatedJobs_
  io_actions_prefix: io_actions_ts_
  storage_svc_prefix: storage_services_operations_
...